### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_payment_method()

### ISSUE THREAD

**Issue by DennisPrins** [MultiSafepay/WooCommerce#13] opened 2021-07-16 09:59 UTC
Hi Multisafepay,

We got the following error massage for version 4.6.0:

`[09-Jul-2021 06:45:07 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_payment_method() on bool in /wp-content/plugins/multisafepay/src/PaymentMethods/PaymentMethodCallback.php:165
Stack trace:
#0 wp-content/plugins/multisafepay/src/PaymentMethods/PaymentMethodsController.php(149): MultiSafepay\WooCommerce\PaymentMethods\PaymentMethodCallback->process_callback()
#1 /wp-includes/class-wp-hook.php(292): MultiSafepay\WooCommerce\PaymentMethods\PaymentMethodsController::deprecated_callback('')
#2 /wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#3 /wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#4 /wp-settings.php(582): do_action('wp_loaded')
#5 /wp-config.php(1 in wp-content/plugins/multisafepay/src/PaymentMethods/PaymentMethodCallback.php on line 165
[09-Jul-2021 16:58:20 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_payment_method() on bool in wp-content/plugins/multisafepay/src/PaymentMethods/PaymentMethodCallback.php:165`

**Comment by Daniel-MultiSafepay** [comment] 2021-07-29 10:16
Hello @DennisPrins 

We are not able to reproduce this behavior on our environment. At least no without extra information.

Please, could you open a ticket via email in integration@multisafepay.com?

From there I will be able to help you and provide support sharing sensitive information if need it. 

In the meantime, I will close this issue in GitHub. If you need it; you can always reopen it. 

Thanks.

**Closed** 2021-07-29 10:16 UTC
