### ISSUE TITLE
Klarna invoice is added to all orders with Klarna set off

### ISSUE THREAD

**Issue by nvomedia** [MultiSafepay/WooCommerce#4] opened 2019-07-24 05:37 UTC
Currently MSP adds an Klarna Invoice link to all of our WC orders. It is added to the order as comment with the following text:

> Klarna Invoice:
> https://online.klarna.com/invoices/.pdf

But, we don't use Klarna at all, it is disabled in the WooCommerce settings and in our MSP portal. I also thinking that this will change the order status to 'created' or 'new', but I can't see any evidence for that for now.

**Comment by Mike-MultiSafepay** [comment] 2019-07-24 13:47
Hi @nvomedia

Currently we can't reproduce this issue. This because we don't have all the necessary information. For know, can you provide us with the following information?

- [ ] Wordpress version.
- [ ] WooCommerce version.
- [ ] MultiSafepay plugin version.
- [ ] MultiSafepay Account Id (This can be found in the [MultiSafepay Control](https://merchant.multisafepay.com/) panel)

**Comment by nvomedia** [comment] 2019-07-24 13:59
* [5.2.2]  Wordpress version.
* [3.6.5]  WooCommerce version.
* [3.0.4]  MultiSafepay plugin version.
* [10246754]  MultiSafepay Account Id (This can be found in the [MultiSafepay Control](https://merchant.multisafepay.com/) panel)

Currently I have disabled the plugin and update the orders seems to be stopped.

**Comment by nvomedia** [comment] 2019-07-25 05:54
> 
> Currently I have disabled the plugin and update the orders seems to be stopped.

Disabling the plugin is not stopping the orders to be updated from different statuses, so that is an different issue, and is not relevant anymore for this case.

**Comment by Mike-MultiSafepay** [comment] 2019-07-25 10:11
I have checked your MultiSafepay plugin version and in version 3.0.4, this was a known issue. This issue have been resolved in the latest release of our WooCommerce plugin. We suggest you to do the following steps.

[Steps]

1. Create a back up of your live environment.
2. Create a staging environment and test your webshop with our latest release.
3. Confirm that the issue has been solved on the staging environment.
4. Update your live environment with your staging environment.
5. Confirm that the issue has been solved on the live environment.

If this issue still persist after updating to the latest release, please reopen this issue.

**Closed by Mike-MultiSafepay** 2019-07-25 10:11 UTC

**Comment by nvomedia** [comment] 2019-07-25 11:29
Strange, I didn't received this update in my Wordpress updates...

**Comment by Mike-MultiSafepay** [comment] 2019-07-25 11:54
Maybe you didn't recieve the notification because we currently don't have a plugin active on the [WooCommerce Extension Marketplace](https://woocommerce.com/product-category/woocommerce-extensions/?q=Multisafepay). 
To update your plugin, I recommend you reading our [WooCommerce documentation](https://docs.multisafepay.com/plugins/woocommerce/manual/).
